class NotFoundError(Exception):
    pass


class UnknownError(Exception):
    pass
